module.exports = {
  business: {
    name: "Prestige - Salon de Coiffure",
    type: "salon de coiffure haut de gamme",
    address: "13, Avenue du Général de Gaulle, 73200 Albertville",
    phone: "07 55 55 10 00",
    whatsapp: "07 55 55 10 00",
    email: "info@Coiffure-Albertville.fr",
    horaires: "Lundi : 9h-19h | Mardi–Vendredi : 8h-18h30 | Samedi : 8h-17h | Dimanche : Fermé",
    histoire: "Salon emblématique depuis 1942, anciennement Centrale Indéfrisable puis Françoise Coiffure, devenu Prestige en 2022. Rénové en 2024.",
    ambiance: "Espace chic et raffiné, fauteuils massants pendant le shampooing, café et thé offerts, atmosphère élégante et détendue.",
    avis: "Note 5/5 sur 736 avis Planity. Accueil, propreté, cadre et qualité tous notés 5/5.",
    equipe: [
      { nom: "Patricia", specialite: "Coupe & coiffage, coiffeuse polyvalente et passionnée" },
      { nom: "Vanessa", specialite: "Spécialiste lissage brésilien et soins reconstructeurs" },
      { nom: "Kévin", specialite: "Balayage, ombré hair, babylights, colorations et éclaircissements" },
      { nom: "Chloé", specialite: "Chignons, tresses, coiffures de mariage et tendances réseaux sociaux" },
      { nom: "Jennifer", specialite: "Dégradé américain, coupes masculines, ombré, balayage, babylights" }
    ],
    services: [
      { nom: "Shampoing + Coiffage cheveux courts", prix: "25€", duree: "25 min" },
      { nom: "Shampoing + Coiffage cheveux mi-longs", prix: "28€", duree: "35 min" },
      { nom: "Shampoing + Coiffage cheveux longs", prix: "à partir de 35€", duree: "45 min" },
      { nom: "Coupe Femme courte", prix: "39€", duree: "30 min" },
      { nom: "Coupe Femme mi-longs", prix: "46€", duree: "40 min" },
      { nom: "Coupe Femme longs", prix: "à partir de 52€", duree: "50 min" },
      { nom: "Coupe Homme classique", prix: "24€", duree: "20 min" },
      { nom: "Coupe Homme dégradé américain", prix: "26€", duree: "30 min" },
      { nom: "Coupe Homme transformation", prix: "à partir de 30€", duree: "30 min" },
      { nom: "Coupe Enfant fille courts", prix: "19€", duree: "30 min" },
      { nom: "Coupe Enfant fille mi-longs", prix: "25€", duree: "40 min" },
      { nom: "Coupe Enfant garçon 0-9 ans", prix: "14€", duree: "25 min" },
      { nom: "Coupe Enfant garçon 10-14 ans", prix: "19€", duree: "20 min" },
      { nom: "Coloration racine courts (Wella)", prix: "60€", duree: "1h30" },
      { nom: "Coloration racine mi-longs", prix: "65€", duree: "1h40" },
      { nom: "Coloration racine longs", prix: "à partir de 75€", duree: "1h50" },
      { nom: "Coloration végétale courts (Super Natural Color Wella)", prix: "75€", duree: "1h40" },
      { nom: "Coloration végétale mi-longs", prix: "80€", duree: "1h50" },
      { nom: "Coloration végétale longs", prix: "à partir de 85€", duree: "2h" },
      { nom: "Coloration végétale cheveux blancs courts", prix: "85€", duree: "2h10" },
      { nom: "Balayage Ombré Baby Light + patine courts", prix: "à partir de 115€", duree: "3h35" },
      { nom: "Balayage Ombré Baby Light + patine mi-longs", prix: "à partir de 145€", duree: "3h50" },
      { nom: "Balayage Ombré Baby Light + patine longs", prix: "à partir de 175€", duree: "4h15" },
      { nom: "Mèches + coiffage courts", prix: "à partir de 101€", duree: "2h25" },
      { nom: "Mèches + coiffage mi-longs", prix: "à partir de 125€", duree: "2h45" },
      { nom: "Coloration + Mèches courts", prix: "110€", duree: "2h" },
      { nom: "Patine courts", prix: "à partir de 55€", duree: "1h15" },
      { nom: "Lissage Brésilien courts - Vanessa", prix: "à partir de 200€", duree: "2h" },
      { nom: "Lissage Brésilien mi-longs - Vanessa", prix: "à partir de 250€", duree: "2h30" },
      { nom: "Lissage Brésilien longs - Vanessa", prix: "à partir de 300€", duree: "3h" },
      { nom: "Lissage Brésilien très longs - Vanessa", prix: "à partir de 400€", duree: "3h30" },
      { nom: "Permanente courts", prix: "70€", duree: "1h25" },
      { nom: "Permanente mi-longs", prix: "83€", duree: "1h45" },
      { nom: "Chignon", prix: "45€ à 65€", duree: "1h" },
      { nom: "Forfait Essai + Chignon Jour J", prix: "150€", duree: "1h30" },
      { nom: "Tresse africaine", prix: "à partir de 15€", duree: "40 min" },
      { nom: "Soin Essentiel", prix: "10€", duree: "10 min" },
      { nom: "Soin Prestige", prix: "à partir de 25€", duree: "25 min" },
      { nom: "Soin SOS Sweet Professionnel", prix: "à partir de 70€", duree: "55 min" },
      { nom: "Soin Cronology Sweet Professionnel", prix: "à partir de 70€", duree: "35 min" },
      { nom: "Conseil & Diagnostic", prix: "à partir de 15€ (déduit de la prochaine prestation)", duree: "15 min" },
      { nom: "Mèches homme dessus tête", prix: "39€", duree: "1h15" },
      { nom: "Défrisage tête entière homme", prix: "59€", duree: "40 min" }
    ],
    rdv_link: "https://www.planity.com/t/SaV",
    message_accueil: "Bonjour ! Bienvenue chez Prestige ✂️ Salon de coiffure à Albertville depuis 1942. Comment puis-je vous aider ?"
  }
};
